const cvData = {
  german: {
    work: {
      bh: {
        company: "Österreichisches Bundesheer",
        job: "Präsenzdienst",
        from: "2002",
        to: "2003",
        description: null,
        points: null,
      },
      vie: {
        company: "Vienna International Airport",
        job: "(Gepäcks-)Lader",
        from: "2003",
        to: "2010",
        description:
          "Geringfügig während Studien-, bzw. Vollzeit während studienfreier Zeit",
        points: null,
      },
      vbw: {
        company: "Burgenländisches Volksbildungswerk",
        job: "Pädagogischer Mitarbeiter",
        from: "10/2010",
        to: "04/2014",
        description: null,
        points: [
          "Betreuung der Bezirksstellen Oberpullendorf (durchgehend), Mattersburg, Neusiedl am See und Jennersdorf (temporär aufgrund von Personalfluktuationen)",
          "Planung, Organisation und tw. Durchführung diverser Erwachsenenbildungsveranstaltungen gemeinsam mit Ortsstellen- und/oder BezirksstellenleiterInnen",
          "Betreuung diverser Theatergruppen",
          "Mitarbeit an vierteljährlich erscheinender Zeitschrift",
          "Umstrukturierung der hauseigenen Bibliothek",
        ],
      },
      hp: {
        company: "Holmes Place Vienna (Selbstständig)",
        job: "Personal trainer",
        from: "09/2014",
        to: "03/2015",
        description: null,
        points: null,
      },
      tw: {
        company: "Teamwork Service GmbH",
        job: "Produktionstechniker",
        from: "03/2015",
        to: "today",
        description:
          "Mitarbeit an Produktionen des ORF in verschiedenen Tätigkeiten:",
        points: [
          "Arbeiten im CMS (Migration und Konvertierung von Videofiles)",
          "Arbeiten am Produktionsserver und an diversen Regieplätzen",
          "Bearbeitung und Bereitstellung sendungsrelevanter Files",
          "Kontrolle und Überwachung der Anlieferung von Videomaterial über diverse Kanäle (Internet, Satellit etc.)",
          "Technische Qualitätskontrolle und Abnahme von Eigen- und Fremdproduktionen",
          "Regelmäßiger Kundenkontakt mit Redakteuren und Arbeit in großen Teams",
        ],
      },
    },
    education: {
      hak: {
        degree: "Matura",
        name: "HAK (Matura)",
        school: "HAK Neusiedl am See",
        start: "09/1997",
        end: "06/2002",
        description: null,
      },
      spowiBakk: {
        degree: "Bakk.rer.nat.",
        name: "Sportmanagement (Bachelor Sportwissenschaften)",
        school: "Universität Wien",
        start: "10/2003",
        end: "03/2009",
        description: null,
      },
      thewi: {
        degree: "BA",
        name: "Theater- Film- und Medienwissenschaft",
        school: "Universität Wien",
        start: "03/2007",
        end: "04/2015",
        description: null,
      },
      spowiMa: {
        degree: null,
        name: null,
        school: "Universität Wien",
        start: null,
        end: null,
        description: "nicht abgeschlossen",
      },
      ph: {
        degree: null,
        name: null,
        school: null,
        start: null,
        end: null,
        description: "nicht abgeschlossen",
      },
      codecool: {
        degree: "Zertifikat",
        name: "Full Stack Developement",
        school: "Codecool Austria GmbH",
        start: "10/2022",
        end: "09/2023",
        description: null,
      },
    },
  },
  english: {
    work: {
      bh: {
        company: "Österreichisches Bundesheer",
        job: "Präsenzdienst",
        from: "2002",
        to: "2003",
        description: null,
        points: null,
      },
      vie: {
        company: "Vienna International Airport",
        job: "Loader",
        from: "2003",
        to: "2010",
        description:
          "Parttime during semesters and fulltime during university vacations",
        points: null,
      },
      vbw: {
        company: "Burgenländisches Volksbildungswerk",
        job: "Educational employee",
        from: "10/2010",
        to: "04/2014",
        description: null,
        points: [
          "Support of the following district offices: Oberpullendorf (continuously), Mattersburg, Neusiedl am See und Jennersdorf (temporarily due to staff turnover",
          "Planning, organisation and implementation of various adult education events together with district office managers",
          "Support of different theatre groups",
          "Assistance on quarterly published magazine",
          "Re-structuring of on-site library",
        ],
      },
      hp: {
        company: "Holmes Place Vienna (self employed)",
        job: "Personal trainer",
        from: "09/2014",
        to: "03/2015",
        description: null,
        points: null,
      },
      tw: {
        company: "Teamwork Service GmbH",
        job: "Production technician",
        from: "03/2015",
        to: "today",
        description:
          "Assistance of ORF productions in various operational activities",
        points: [
          "CMS tasks (migration and conversion of video files)",
          "Operational activities on production server as well as on different direction sets",
          "Administration and deployment of broadcast relevant files",
          "Controlling and monitoring of video material delivery via different channels (internet, satellite etc.)",
          "Technical quality control and apporval of internal and external productions",
          "Regular customer contact with editors and work in big teams",
        ],
      },
    },
    education: {
      hak: {
        degree: "Matura",
        name: "HAK (Matura)",
        school: "HAK Neusiedl am See",
        start: "09/1997",
        end: "06/2002",
        description: null,
      },
      spowiBakk: {
        degree: "Bakk.rer.nat.",
        name: "Sports Management (Sport Science)",
        school: "University of Vienna",
        start: "10/2003",
        end: "03/2009",
        description: null,
      },
      thewi: {
        degree: "BA",
        name: "Theatre, Film and Media Studies",
        school: "University of Vienna",
        start: "03/2007",
        end: "04/2015",
        description: null,
      },
      spowiMa: {
        degree: null,
        name: null,
        school: "University of Vienna",
        start: null,
        end: null,
        description: "nicht abgeschlossen",
      },
      ph: {
        degree: null,
        name: null,
        school: null,
        start: null,
        end: null,
        description: "nicht abgeschlossen",
      },
      codecool: {
        degree: "Certificate",
        name: "Full Stack Development",
        school: "Codecool Austria GmbH",
        start: "10/2022",
        end: "09/2023",
        description: null,
      },
    },
  },
};

export default cvData;
